// Auto-generated by tools/gen_app_registry.py; do not edit by hand.
#ifndef BUZZOS_APP_REGISTRY_H
#define BUZZOS_APP_REGISTRY_H

#include <stddef.h>

struct app_seed_entry {
    const char *path;
    const void *data;
    size_t size;
    int refresh;
};

static const char app_textedit_manifest[] =
    "name=TextEdit\n"
    "kind=gui\n"
    "version=1\n"
    "summary=Plain text editor\n"
    "exec=/fs/apps/textedit\n"
    "state=/fs/textedit.txt\n"
    "source=src/user/bin/textedit.c\n"
    "readme=/fs/apps/textedit.readme\n";

static const char app_textedit_readme[] =
    "TextEdit is a BuzzOS GUI text editor.\n"
    "\n"
    "Open and Save use /fs/textedit.txt.\n";

static const char app_textedit_seed[] =
    "Welcome to BuzzOS TextEdit.\n"
    "\n"
    "This is a user-space GUI app running in a desktop window.\n";

static const char app_paint_manifest[] =
    "name=Paint\n"
    "kind=gui\n"
    "version=1\n"
    "summary=Bitmap paint app\n"
    "exec=/fs/apps/paint\n"
    "state=/fs/paint.seed\n"
    "source=src/user/bin/paint.c\n"
    "readme=/fs/apps/paint.readme\n";

static const char app_paint_readme[] =
    "Paint is a BuzzOS GUI drawing app.\n"
    "\n"
    "Tools: brush, eraser, line, rectangle, fill, color palette.\n";

static const char app_paint_seed[] =
    "Paint stores its canvas in memory for this version.\n";

static const char app_calculator_manifest[] =
    "name=Calculator\n"
    "kind=gui\n"
    "version=1\n"
    "summary=Expression calculator\n"
    "exec=/fs/apps/calculator\n"
    "state=/fs/calculator.seed\n"
    "source=src/user/bin/calculator.c\n"
    "readme=/fs/apps/calculator.readme\n";

static const char app_calculator_readme[] =
    "Calculator is a BuzzOS GUI calculator.\n"
    "\n"
    "It supports +, -, *, /, %, parentheses, decimals, and sqrt().\n";

static const char app_calculator_seed[] =
    "Calculator has no persistent state yet.\n";

static const struct app_seed_entry app_seed_entries[] = {
    { "/fs/apps/textedit", initrd_bin_textedit_data, INITRD_BIN_TEXTEDIT_SIZE, 1 },
    { "/fs/apps/textedit.app", app_textedit_manifest, sizeof(app_textedit_manifest) - 1, 1 },
    { "/fs/apps/textedit.readme", app_textedit_readme, sizeof(app_textedit_readme) - 1, 0 },
    { "/fs/textedit.txt", app_textedit_seed, sizeof(app_textedit_seed) - 1, 0 },
    { "/fs/apps/paint", initrd_bin_paint_data, INITRD_BIN_PAINT_SIZE, 1 },
    { "/fs/apps/paint.app", app_paint_manifest, sizeof(app_paint_manifest) - 1, 1 },
    { "/fs/apps/paint.readme", app_paint_readme, sizeof(app_paint_readme) - 1, 0 },
    { "/fs/paint.seed", app_paint_seed, sizeof(app_paint_seed) - 1, 0 },
    { "/fs/apps/calculator", initrd_bin_calculator_data, INITRD_BIN_CALCULATOR_SIZE, 1 },
    { "/fs/apps/calculator.app", app_calculator_manifest, sizeof(app_calculator_manifest) - 1, 1 },
    { "/fs/apps/calculator.readme", app_calculator_readme, sizeof(app_calculator_readme) - 1, 0 },
    { "/fs/calculator.seed", app_calculator_seed, sizeof(app_calculator_seed) - 1, 0 },
};
static const size_t app_seed_entry_count = 12;

#endif /* BUZZOS_APP_REGISTRY_H */
