param(
    [string]$Out = "src/kernel/drv/font_builtin.h",
    [string]$FontFile = "",
    [int]$CellWidth = 12,
    [int]$CellHeight = 22,
    [int]$FontSize = 17,
    [int]$OffsetX = -1,
    [int]$OffsetY = -2,
    [int]$Threshold = 24,
    [double]$Embolden = 0.45,
    [bool]$Monochrome = $true
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Add-Type -AssemblyName System.Drawing

if ($FontFile -eq "") {
    $candidates = @(
        "C:\Windows\Fonts\CascadiaMono.ttf",
        "C:\Windows\Fonts\consola.ttf",
        "C:\Windows\Fonts\lucon.ttf",
        "C:\Windows\Fonts\cour.ttf"
    )
    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) {
            $FontFile = $candidate
            break
        }
    }
}

if ($FontFile -eq "" -or -not (Test-Path $FontFile)) {
    throw "No usable monospace font found"
}

$outPath = [System.IO.Path]::GetFullPath($Out)
$outDir = [System.IO.Path]::GetDirectoryName($outPath)
[System.IO.Directory]::CreateDirectory($outDir) | Out-Null

$pfc = New-Object System.Drawing.Text.PrivateFontCollection
$pfc.AddFontFile($FontFile)
$family = $pfc.Families[0]
$font = New-Object System.Drawing.Font($family, [single]$FontSize, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$brush = [System.Drawing.Brushes]::White
$format = [System.Drawing.StringFormat]::GenericTypographic.Clone()
$format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::MeasureTrailingSpaces

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("/* Generated by tools/gen_kernel_font.ps1. Do not edit by hand. */")
$lines.Add("#ifndef BUZZOS_FONT_BUILTIN_H")
$lines.Add("#define BUZZOS_FONT_BUILTIN_H")
$lines.Add("")
$lines.Add("#include <stdint.h>")
$lines.Add("")
$lines.Add("enum {")
$lines.Add("    KFONT_FIRST = 32,")
$lines.Add("    KFONT_COUNT = 95,")
$lines.Add("    KFONT_WIDTH = $CellWidth,")
$lines.Add("    KFONT_HEIGHT = $CellHeight,")
$lines.Add("};")
$lines.Add("")
$lines.Add("static const uint8_t kfont_alpha[KFONT_COUNT][KFONT_HEIGHT][KFONT_WIDTH] = {")

for ($code = 32; $code -le 126; $code++) {
    $ch = [char]$code
    $bmp = New-Object System.Drawing.Bitmap($CellWidth, $CellHeight, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::Black)
    if ($Monochrome) {
        $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
    } else {
        $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
    }
    $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::Half
    $g.DrawString([string]$ch, $font, $brush, [single]$OffsetX, [single]$OffsetY, $format)

    $escaped = if ($ch -eq '\') { "\\" } elseif ($ch -eq "'") { "\'" } else { [string]$ch }
    $lines.Add("    /* $code '$escaped' */ {")
    for ($y = 0; $y -lt $CellHeight; $y++) {
        $vals = New-Object System.Collections.Generic.List[string]
        for ($x = 0; $x -lt $CellWidth; $x++) {
            $c = $bmp.GetPixel($x, $y)
            $a = [double](($c.R + $c.G + $c.B) / 3)
            if ($x -gt 0) {
                $lc = $bmp.GetPixel($x - 1, $y)
                $la = [double](($lc.R + $lc.G + $lc.B) / 3) * $Embolden
                if ($la -gt $a) { $a = $la }
            }
            if ($Monochrome) {
                $a = if ($a -ge $Threshold) { 255 } else { 0 }
            } else {
                if ($a -gt 0) {
                    $a = [Math]::Pow($a / 255.0, 0.70) * 255.0
                }
                if ($a -gt 255) { $a = 255 }
                $a = [int][Math]::Round($a)
            }
            $vals.Add($a.ToString())
        }
        $lines.Add("        {" + [string]::Join(",", $vals) + "},")
    }
    $lines.Add("    },")
    $g.Dispose()
    $bmp.Dispose()
}

$lines.Add("};")
$lines.Add("")
$lines.Add("#endif /* BUZZOS_FONT_BUILTIN_H */")

[System.IO.File]::WriteAllLines($outPath, $lines, [System.Text.Encoding]::ASCII)
Write-Host "Generated $outPath from $FontFile ($CellWidth x $CellHeight, size $FontSize)"
