import re
import sys


def ident(path):
    name = path.strip("/")
    if not name:
        name = "root"
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return "initrd_" + name


def emit(name, file_path):
    with open(file_path, "rb") as f:
        data = f.read()

    var = ident(name)
    print(f"#define {var.upper()}_SIZE {len(data)}")
    print(f'static const uint8_t {var}_data[{var.upper()}_SIZE] __attribute__((used)) = {{')
    for i in range(0, len(data), 16):
        line = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        print(f"    {line},")
    print("};")
    print("")


print("// Auto-generated by tools/mkinitrd.py")

if len(sys.argv) == 2:
    emit("init", sys.argv[1])
elif len(sys.argv) > 2 and len(sys.argv[1:]) % 2 == 0:
    args = sys.argv[1:]
    for i in range(0, len(args), 2):
        emit(args[i], args[i + 1])
else:
    raise SystemExit("usage: mkinitrd.py <elf> OR mkinitrd.py <path> <elf> ...")
